# Generated by Django 2.1 on 2018-08-28 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(max_length=200)),
                ('point', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info_text', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='')),
                ('star', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='achievement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.Task'),
        ),
    ]
